config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }
  post 'links', to: 'links#create', as: :create_link
  patch 'links/:id' => 'links#update', as: :update_link
  delete 'links/:id', to: 'links#destroy', as: :destroy_link

  get 'dashboard', to: 'dashboard#index'
  get 'appearance', to: 'dashboard#appearance'
  root 'dashboard#index'

  get ':id', to: 'dashboard#show', as: :user
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!, only: %i[index appearance]
  before_action :set_user, only: [:show]
  before_action :render_navbar, except: [:show]

  def index
  end

  def appearance
  end

  def show
    redirect_to dashboard_path if @user.nil?

    @links = @user.links.where.not(url: '', title: '')
  end

  private
    def render_navbar
      @render_navbar = true
    end

    def set_user
      begin
        @user = User.friendly.find(params[:id])
      rescue StandartError
        @user = nil
      end
    end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/appearance.html.erb
<div class="container">
  <h1 class="text-center">Appearance Page</h1>

  <%= simple_form_for(current_user, url: registration_path(current_user), html: { method: :put }, data: { turbo: false }) do |f| %>
    <div class="row">
      <div class="col-8">
        <div class="row mt-3 align-items-center">
          <div class="col-6 text-center">
            <%= image_tag(current_user.avatar, class: "avatar-image") if current_user.avatar.attached? %>
          </div>
          <div class="col-6">
            <%= f.input :avatar, required: false, label: false %>
          </div>
        </div>

        <div class="row mt-4 text-center">
          <div class="col-6 no-padding-col">
            <%= f.input :full_name, placeholder: "Your full name...", label: false, class: "form-control", required: false %>
          </div>
          <div class="col-6 no-padding-col text-right">
            <div class="input-group justify-content-end">
              <span class="input-group-text mb-3">@</span>
              <%= f.input :username, placeholder: "Your username...", label: false, required: true, class: "form-control" %>
            </div>
          </div>
        </div>

        <div class="row mt-5">
          <div class="col no-padding-col">
            <div class="input-group row w-auto">
                <%= f.input :body, placeholder: "About you...", label: false, class: "form-control", required: false %>
            </div>
          </div>
        </div>

        <div class="mt-2 text-center">
          <%= f.submit "Update Profile", class: "btn btn-primary" %>
        </div>
      </div>

      <div class="col-4">
      </div>
  </div>
  <% end %>
</div>

app/views/dashboard/index.html.erb
<div class="container my-3">
  <div class="row">
    <div class="col-3"></div>
    <div class="col-6">
      <h1 class="text-center">Link Manager</h1>
      <% current_user.links.each do |link| %>
        <div class="row">
          <div class="col-10">
            <%= simple_form_for(link, url: update_link_url(link)) do |f| %>
              <div class="mb-4">
                <%= f.input :title, placeholder: "Title", label: false, class: "form-control" %>
                <%= f.input :url, placeholder: "URL", label: false, class: "form-control" %>
                <%= f.submit "Update Link", class: "btn btn-primary me-auto" %>
              </div>
            <% end %>
          </div>
          <div class="col-2 text-end">
            <%= button_to destroy_link_path(link.id), method: :delete, class: "btn btn-danger" do %>
              <i class="bi bi-trash3-fill"></i>
            <% end %>
          </div>
        </div>
      <% end %>

      <%= button_to "Add Link", create_link_path, class: "btn btn-lg btn-success w-100" %>
    </div>
    <div class="col-3"></div>
  </div>
</div>

app/views/dashboard/show.html.erb
<div class="profile-page">
  <div class="container">
    <div class="row">
      <div class="col-1"></div>
      <div class="col-10">
        <div class="row mt-5">
          <div class="d-flex justify-content-center">
            <%= image_tag(@user.avatar, class: "avatar-image") if @user.avatar.present? %>
          </div>
          <div class="d-flex justify-content-center mt-4">
            <h2 class="white-font"><%= @user.full_name %></h2>
          </div>
          <div class="d-flex justify-content-center">
            <p class="white-font"><%= @user.body %></p>
          </div>
        </div>
      </div>
      <div class="col-1"></div>
    </div>

    <div class="row">
      <div class="col-1"></div>
      <div class="col-10">
        <% @links.each do |link| %>
          <div class="row">
            <div class="col-12 d-flex justify-content-center">
              <%= link_to link.url, target: "_blank", class: "linkable btn btn-secondary" do %>
                <span class="linkable-span"><%= link.title %></span>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
      <div class="col-1"></div>
    </div>
  </div>
</div>