config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }
  post 'links', to: 'links#create', as: :create_link
  patch 'links/:id' => 'links#update', as: :update_link
  delete 'links/:id', to: 'links#destroy', as: :destroy_link

  get 'dashboard', to: 'dashboard#index'
  get 'appearance', to: 'dashboard#appearance'
  root 'dashboard#index'

  get ':id', to: 'dashboard#show', as: :user
end

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%= link_to "Linktree", dashboard_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Appearance", appearance_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "My Page", user_path(current_user.username), class: "nav-link" %>
        </li>
      </ul>

      <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= current_user.username %>
          </a>
          <ul class="dropdown-menu dropdown-menu-end">
            <li><%= link_to "My Account", edit_user_registration_path, class: "dropdown-item" %></li>
            <li><hr class="dropdown-divider"></li>
            <li>
              <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: "delete" }, class: "dropdown-item" %>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LinktreeRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render partial: "layouts/navbar" if @render_navbar %>
    <%= render partial: "layouts/alerts" %>
    <%= yield %>
  </body>
</html>